/*
 * This source file was generated by the Gradle 'init' task
 */
package app.src.test.java.mc322;

import app.src.main.java.mc322.App;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("aaaa");
    }
}
