/*
 * This source file was generated by the Gradle 'init' task
 */
package mc322;

import org.junit.jupiter.api.Test;

import mc322.ui.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("aaaa");
    }
}
