/*
 * This source file was generated by the Gradle 'init' task
 */
package mc322;

import java.time.LocalDateTime;

// Ensure this import matches the actual package of GerenciadorDeEventos
import mc322.evento.GerenciadorDeEventos;
import mc322.usuario.Usuario;

public class App {
    public static void main(String[] args) {
        GerenciadorDeEventos gerenciador = new GerenciadorDeEventos();
        Usuario usuario = new Usuario("Bruno", "sabasbruno132@gmail.com", "AmargoAzedo");
        gerenciador.criarEvento(usuario, "Reunião", "CB03", "06/05/2025", "15:00", 120, "Lehilton", "IC", false);
        System.out.println(usuario.getEventos().get(0).getCaracteristicaEvento());
    }
}
