/*
 * This source file was generated by the Gradle 'init' task
 */
package app.src.main.java.mc322;

import java.time.LocalDateTime;

// Ensure this import matches the actual package of GerenciadorDeEventos
import app.src.main.java.mc322.evento.GerenciadorDeEventos;
import app.src.main.java.mc322.usuario.Usuario;

public class App {
    public static void main(String[] args) {
        GerenciadorDeEventos gerenciador = new GerenciadorDeEventos();
        Usuario usuario = new Usuario("Bruno", "sabasbruno132@gmail.com", "AmargoAzedo");
        LocalDateTime dataHora = LocalDateTime.of(2025, 6, 21, 19, 0); //Precisamos que isso seja administrado dentro do gerenciador
        gerenciador.criarEvento(usuario, "Reunião", "CB03", dataHora, 120, "Lehilton", "IC", false);
        System.out.println(usuario.getEventos().get(0).getCaracteristicaEvento());
    }
}
